Repository scratchaddons-community/scradd, pull requests merged in 2023-09, with the labels that each got.

#368 Leaderboard button in /xp rank!!!!!!
  modules/xp/index.ts
  modules/xp/rank.ts
Labels: scope: patch, difficulty: easy

#301 Answered suggestion alerts
  modules/suggestions/index.ts
  modules/suggestions/misc.ts
  util/numbers.ts
Labels: scope: minor

#317 Cross-server support
  .eslintrc.cjs
  README.md
  common/config.ts
  common/constants.ts
  common/database.ts
  modules/addon.ts
  modules/automod/automod.ts
  modules/automod/index.ts
  modules/automod/language.ts
  modules/board/explore.ts
  modules/board/index.ts
  modules/board/misc.ts
  modules/board/update.ts
  modules/bot/edit.ts
  modules/bot/index.ts
  modules/bot/info.ts
  modules/bot/say.ts
  modules/games/addonQuestions.ts
  modules/games/guessAddon.ts
  modules/games/index.ts
  modules/games/memoryMatch.ts
  modules/logging/misc.ts
  modules/notifs.ts
  modules/poll.ts
  modules/punishments/ban.ts
  modules/punishments/strikes.ts
  modules/purge.ts
  modules/reminders/index.ts
  modules/reminders/management.ts
  modules/reminders/misc.ts
  modules/reminders/send.ts
  modules/secrets/index.ts
  modules/settings.ts
  modules/suggestions/index.ts
  modules/suggestions/top.ts
  modules/threads/index.ts
  modules/tickets/index.ts
  modules/userInfo.ts
  modules/xp/giveXp.ts
  modules/xp/index.ts
  package-lock.json
  package.json
  util/discord.ts
Labels: scope: major

#321 remove the memory match tourney code
  modules/games/memoryMatch.ts
  modules/games/tourney.ts
Labels: scope: patch, status: ready to merge

#367 tons of menu commands!
  modules/board/explore.ts
  modules/board/index.ts
  modules/bot/index.ts
  modules/bot/say.ts
  modules/games/index.ts
  modules/games/memoryMatch.ts
  modules/punishments/ban.ts
  modules/punishments/index.ts
  modules/punishments/strikes.ts
  modules/purge.ts
  modules/suggestions/index.ts
  modules/tickets/contact.ts
  modules/tickets/index.ts
  modules/userInfo.ts
  modules/xp/index.ts
  modules/xp/rank.ts
  package-lock.json
Labels: scope: major, status: ready to merge, difficulty: medium

#343 Scratch page fetching
  .eslintrc.cjs
  .github/workflows/deploy.yml
  common/constants.ts
  modules/auto/index.ts
  modules/auto/scratch.ts
  modules/auto/secrets.ts
  modules/bot/info.ts
  modules/games/memoryMatch.ts
  modules/settings.ts
  package-lock.json
  package.json
Labels: scope: minor, difficulty: medium

#383 Node 20 (v3.0)
  .eslintrc.cjs
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  common/database.ts
  common/extension.ts
  index.ts
  modules/automod/automod.ts
  modules/automod/index.ts
  modules/automod/language.ts
  modules/automod/nicknames.ts
  modules/board/explore.ts
  modules/board/misc.ts
  modules/board/update.ts
  modules/bot/info.ts
  modules/bot/say.ts
  modules/games/guessAddon.ts
  modules/games/hangman.ts
  modules/games/memoryMatch.ts
  modules/logging/misc.ts
  modules/modInterestForm.ts
  modules/punishments/misc.ts
  modules/punishments/strikes.ts
  modules/reminders/management.ts
  modules/reminders/misc.ts
  modules/reminders/send.ts
  modules/roles/custom.ts
  modules/settings.ts
  modules/suggestions/top.ts
  modules/xp/giveXp.ts
  modules/xp/graph.ts
  modules/xp/index.ts
  modules/xp/misc.ts
  modules/xp/rank.ts
  modules/xp/weekly.ts
  package-lock.json
  package.json
  util/discord.ts
  util/numbers.ts
Labels: scope: minor, difficulty: easy

#379 Change Thread Mode default dependency to user app
  modules/games/index.ts
  modules/games/memoryMatch.ts
Labels: scope: patch, difficulty: easy
